name: My Workflow

on:
  push:
  workflow_dispatch:
    inputs:
        myValues:
            description: 'Input Values'

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
  count-args:
    runs-on: ubuntu-latest
    steps:
      - id: report-count
        uses: eliteGoblin/custom_gha_playground@v1
        with:
            arguments-to-count: ${{ github.event.inputs.myValues }}

      - shell: bash
        run: |
            echo argument count is ${{ steps.report-count.outputs.arg-count }}

    #   - name: Hello world action step
    #     uses: eliteGoblin/custom_gha_playground@v1
    #     id: hello
    #     with:
    #         who-to-greet: 'Mona the Octocat'
    #     # Use the output from the `hello` step
    #   - name: Get the output time
    #     run: echo "The time was ${{ steps.hello.outputs.time }}"